default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  webapp
#  username:  <%= Figaro.env.db_username %>
  password:  webapp
#  password:  <%= Figaro.env.db_password %>

development:
  <<: *default
  database: myStore_development
  host: localhost

test:
  <<: *default
  database: myStore_test
  host: localhost

production:
  <<: *default
  database: myStore_production
  username: myStore
  password: <%= ENV['MYSTORE_DATABASE_PASSWORD'] %>
